//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.28 at 09:05:53 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.webservicesoap.org/echo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.webservicesoap.echo;
