POST http://localhost:8080/spring-0.0.1-SNAPSHOT/ws
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:us="http://www.webservicesoap.org/birthday">
    <soapenv:Header/>
    <soapenv:Body>
        <us:getBirthdayRequest>
            <us:day>7</us:day>
            <us:month>10</us:month>
            <us:year>1963</us:year>
            <us:name>JoAnn</us:name>
        </us:getBirthdayRequest>
    </soapenv:Body>
</soapenv:Envelope>