POST http://localhost:8080/spring-0.0.1-SNAPSHOT/ws
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:us="http://www.webservicesoap.org/echo">
    <soapenv:Header/>
    <soapenv:Body>
        <us:getEchoRequest>
            <us:stringToEcho>*JoAnn*</us:stringToEcho>
        </us:getEchoRequest>
    </soapenv:Body>
</soapenv:Envelope>